version: 2

models:
    - name: buses
      description: "A dbt model for Bus types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: cars
      description: "A dbt model for Car types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null


    - name: Motorcycles
      description: "A dbt model for Motorcycle types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: heavy_vehicles
      description: "A dbt model for Heavy Vehicle types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

